package sn.gestionimmobiliere.backend.lease.application;
import java.time.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import sn.gestionimmobiliere.backend.billing.application.BillingService;import sn.gestionimmobiliere.backend.lease.api.*;import sn.gestionimmobiliere.backend.lease.domain.*;import sn.gestionimmobiliere.backend.lease.infrastructure.LeaseRepository;import sn.gestionimmobiliere.backend.owner.application.OwnerProperties;import sn.gestionimmobiliere.backend.tenant.application.TenantService;import sn.gestionimmobiliere.backend.unit.application.UnitService;
@Service public class LeaseService{
	private final LeaseRepository repository;private final UnitService units;private final TenantService tenants;private final BillingService billing;private final OwnerProperties props;private final Clock clock;public LeaseService(LeaseRepository r,UnitService u,TenantService t,BillingService b,OwnerProperties p,Clock c){repository=r;units=u;tenants=t;billing=b;props=p;clock=c;}
	@Transactional public LeaseResponse create(CreateLeaseRequest r){if(r.endDate()!=null&&r.endDate().isBefore(r.startDate()))throw new LeaseConflictException("La date de fin precede la date de debut");units.entity(r.unitId());tenants.entity(r.tenantId());if(repository.existsByUnitIdAndOrganizationIdAndStatus(r.unitId(),props.organizationId(),LeaseStatus.ACTIVE))throw new LeaseConflictException("Cette unite possede deja un bail actif");Instant now=clock.instant();Lease l=repository.saveAndFlush(new Lease(UUID.randomUUID(),props.organizationId(),r.unitId(),r.tenantId(),r.startDate(),r.endDate(),r.monthlyRent(),r.depositAmount(),r.dueDay(),LeaseStatus.ACTIVE,now));units.occupy(r.unitId());billing.createCharge(l.getId(),r.startDate(),r.monthlyRent(),r.dueDay());return map(l);}
	@Transactional(readOnly=true) public Page<LeaseResponse> all(Pageable p){return repository.findAllByOrganizationId(props.organizationId(),p).map(this::map);}
	@Transactional(readOnly=true) public LeaseResponse one(UUID id){return map(entity(id));}
	@Transactional public LeaseResponse terminate(UUID id,LocalDate date){Lease l=entity(id);if(l.getStatus()!=LeaseStatus.ACTIVE)throw new LeaseConflictException("Seul un bail actif peut etre termine");l.terminate(date,clock.instant());units.release(l.getUnitId());return map(repository.saveAndFlush(l));}
	public Lease entity(UUID id){return repository.findByIdAndOrganizationId(id,props.organizationId()).orElseThrow(()->new LeaseNotFoundException(id));}
	private LeaseResponse map(Lease l){return new LeaseResponse(l.getId(),l.getUnitId(),l.getTenantId(),l.getStartDate(),l.getEndDate(),l.getMonthlyRent(),l.getDepositAmount(),l.getDueDay(),l.getStatus(),l.getCreatedAt(),l.getUpdatedAt());}
}
