package sn.gestionimmobiliere.backend.billing.application;
import java.time.*;import java.util.*;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import sn.gestionimmobiliere.backend.billing.api.*;import sn.gestionimmobiliere.backend.billing.domain.*;import sn.gestionimmobiliere.backend.billing.infrastructure.*;import sn.gestionimmobiliere.backend.owner.application.OwnerProperties;
@Service public class BillingService{
	private final RentChargeRepository charges;private final PaymentRepository payments;private final OwnerProperties props;private final Clock clock;public BillingService(RentChargeRepository c,PaymentRepository p,OwnerProperties o,Clock k){charges=c;payments=p;props=o;clock=k;}
	@Transactional public RentCharge createCharge(UUID leaseId,LocalDate start,long amount,int dueDay){LocalDate period=start.withDayOfMonth(1);LocalDate due=period.withDayOfMonth(dueDay);RentCharge c=new RentCharge(UUID.randomUUID(),props.organizationId(),leaseId,period,due,amount,today(),clock.instant());return charges.saveAndFlush(c);}
	@Transactional(readOnly=true) public Page<RentChargeResponse> all(Pageable p){return charges.findAllByOrganizationId(props.organizationId(),p).map(this::map);}
	@Transactional(readOnly=true) public RentChargeResponse one(UUID id){return map(entity(id));}
	@Transactional public PaymentResponse pay(UUID id,CreatePaymentRequest r,String idempotencyKey){UUID org=props.organizationId();String key=normalizeKey(idempotencyKey);RentCharge c=charges.findForPayment(id,org).orElseThrow(()->new RentChargeNotFoundException(id));Optional<Payment> previous=payments.findByOrganizationIdAndIdempotencyKey(org,key);if(previous.isPresent()){if(!previous.get().getRentChargeId().equals(id))throw new PaymentConflictException("La cle d'idempotence est deja utilisee pour une autre echeance");return map(previous.get());}try{c.pay(r.amount(),today(),clock.instant());charges.save(c);return map(payments.saveAndFlush(new Payment(UUID.randomUUID(),org,id,key,r.amount(),r.paymentDate(),r.method(),r.reference(),clock.instant())));}catch(IllegalArgumentException e){throw new PaymentConflictException(e.getMessage());}catch(DataIntegrityViolationException e){throw new PaymentConflictException("Ce paiement a deja ete enregistre");}}
	@Transactional(readOnly=true) public List<PaymentResponse> payments(UUID id){UUID org=props.organizationId();entity(id);return payments.findAllByRentChargeIdAndOrganizationIdOrderByPaymentDateDesc(id,org).stream().map(this::map).toList();}
	@Transactional public int refreshOverdue(){List<RentCharge> list=charges.findAllByOrganizationIdAndStatusIn(props.organizationId(),List.of(ChargeStatus.UPCOMING,ChargeStatus.DUE,ChargeStatus.PARTIAL,ChargeStatus.OVERDUE));list.forEach(c->c.refresh(today(),clock.instant()));charges.saveAll(list);return list.size();}
	public RentCharge entity(UUID id){return charges.findByIdAndOrganizationId(id,props.organizationId()).orElseThrow(()->new RentChargeNotFoundException(id));}
	private RentChargeResponse map(RentCharge c){c.refresh(today(),clock.instant());return new RentChargeResponse(c.getId(),c.getLeaseId(),c.getPeriodStart(),c.getDueDate(),c.getAmountDue(),c.getAmountPaid(),c.getBalance(),c.getStatus(),c.getCreatedAt(),c.getUpdatedAt());}
	private PaymentResponse map(Payment p){return new PaymentResponse(p.getId(),p.getRentChargeId(),p.getAmount(),p.getPaymentDate(),p.getMethod(),p.getReference(),p.getStatus(),p.getCreatedAt());}
	private String normalizeKey(String key){if(key==null||key.isBlank()||key.length()>100)throw new PaymentConflictException("Une cle d'idempotence valide est obligatoire");return key.trim();}
	private LocalDate today(){return LocalDate.now(clock.withZone(ZoneId.of("Africa/Dakar")));}
}
