package sn.gestionimmobiliere.backend.lease.domain;
import java.time.*;import java.util.UUID;import jakarta.persistence.*;
@Entity @Table(name="leases") public class Lease{
	@Id private UUID id;@Column(name="organization_id",nullable=false)private UUID organizationId;@Column(name="unit_id",nullable=false)private UUID unitId;@Column(name="tenant_id",nullable=false)private UUID tenantId;
	@Column(name="start_date",nullable=false)private LocalDate startDate;@Column(name="end_date")private LocalDate endDate;@Column(name="monthly_rent",nullable=false)private long monthlyRent;@Column(name="deposit_amount",nullable=false)private long depositAmount;@Column(name="due_day",nullable=false)private int dueDay;@Enumerated(EnumType.STRING)private LeaseStatus status;@Column(name="created_at")private Instant createdAt;@Column(name="updated_at")private Instant updatedAt;
	protected Lease(){}public Lease(UUID id,UUID organizationId,UUID unitId,UUID tenantId,LocalDate startDate,LocalDate endDate,long monthlyRent,long depositAmount,int dueDay,LeaseStatus status,Instant now){this.id=id;this.organizationId=organizationId;this.unitId=unitId;this.tenantId=tenantId;this.startDate=startDate;this.endDate=endDate;this.monthlyRent=monthlyRent;this.depositAmount=depositAmount;this.dueDay=dueDay;this.status=status;this.createdAt=now;this.updatedAt=now;}
	public void terminate(LocalDate date,Instant now){status=LeaseStatus.TERMINATED;endDate=date;updatedAt=now;}
	public UUID getId(){return id;}public UUID getOrganizationId(){return organizationId;}public UUID getUnitId(){return unitId;}public UUID getTenantId(){return tenantId;}public LocalDate getStartDate(){return startDate;}public LocalDate getEndDate(){return endDate;}public long getMonthlyRent(){return monthlyRent;}public long getDepositAmount(){return depositAmount;}public int getDueDay(){return dueDay;}public LeaseStatus getStatus(){return status;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}
}
