import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { Alert, AppBar, Autocomplete, Box, Button, Card, CardContent, Container, Dialog, DialogActions, DialogContent, DialogTitle, Drawer, Grid, List, ListItemButton, ListItemText, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Toolbar, Typography } from '@mui/material'
import { api, session, type Page, xof } from './api'

type Entity = Record<string, unknown> & { id: string }
type Lookup = { endpoint: string; labelKey: string; secondaryKey?: string }
type Field = { key: string; label: string; type?: string; options?: string[]; lookup?: Lookup }
const nav = [['/', 'Tableau de bord'], ['/owners', 'Propriétaires'], ['/properties', 'Biens'], ['/units', 'Unités'], ['/tenants', 'Locataires'], ['/leases', 'Baux'], ['/billing', 'Loyers']]

function useEntities(endpoint: string) {
  const [rows, setRows] = useState<Entity[]>([])
  useEffect(() => { api<Page<Entity>>(`${endpoint}?size=100`).then(page => setRows(page.content)).catch(() => setRows([])) }, [endpoint])
  return rows
}

function Login() {
  const navigate = useNavigate(); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const result = await api<{ accessToken: string }>('/api/auth/login', { method: 'POST', body: JSON.stringify({ email: data.get('email'), password: data.get('password') }) }); session.save(result.accessToken); navigate('/') } catch (e) { setError((e as Error).message) } }
  return <Box sx={{ minHeight: '100vh', display: 'grid', placeItems: 'center', p: 2 }}><Paper sx={{ p: 4, width: '100%', maxWidth: 420 }}><Typography variant="h4" sx={{ fontWeight: 800 }}>Gestion immobilière</Typography><Typography sx={{ color: 'text.secondary', mb: 3 }}>Espace gestionnaire</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Stack component="form" onSubmit={submit} spacing={2}><TextField name="email" label="Email" autoComplete="username" required /><TextField name="password" label="Mot de passe" type="password" autoComplete="current-password" required /><Button type="submit" variant="contained" size="large">Se connecter</Button></Stack></Paper></Box>
}

function Shell({ children }: { children: ReactNode }) {
  const navigate = useNavigate(); const [mobileOpen, setMobileOpen] = useState(false)
  const menu = <List sx={{ width: 240 }}>{nav.map(([to, label]) => <ListItemButton key={to} component={NavLink} to={to} onClick={() => setMobileOpen(false)}><ListItemText primary={label} /></ListItemButton>)}</List>
  return <Box><AppBar position="fixed"><Toolbar><Button color="inherit" sx={{ display: { xs: 'block', md: 'none' }, mr: 1 }} onClick={() => setMobileOpen(true)}>Menu</Button><Typography variant="h6" sx={{ flexGrow: 1 }}>Real Estate SaaS Sénégal</Typography><Button color="inherit" onClick={() => { session.clear(); navigate('/login') }}>Déconnexion</Button></Toolbar></AppBar><Drawer variant="temporary" open={mobileOpen} onClose={() => setMobileOpen(false)} sx={{ display: { xs: 'block', md: 'none' } }}>{menu}</Drawer><Drawer variant="permanent" sx={{ display: { xs: 'none', md: 'block' }, '& .MuiDrawer-paper': { mt: 8 } }}>{menu}</Drawer><Box component="main" sx={{ ml: { md: '240px' }, pt: 11, pb: 5 }}><Container maxWidth="xl">{children}</Container></Box></Box>
}

function Dashboard() {
  const [data, setData] = useState<Record<string, number>>({}); const [error, setError] = useState('')
  useEffect(() => { api<Record<string, number>>('/api/dashboard/summary').then(setData).catch(e => setError(e.message)) }, [])
  const cards = [['owners', 'Propriétaires'], ['properties', 'Biens'], ['units', 'Unités'], ['tenants', 'Locataires'], ['activeLeases', 'Baux actifs'], ['expectedRent', 'Loyers attendus'], ['collectedRent', 'Loyers encaissés'], ['unpaidRent', 'Impayés échus']]
  return <><Typography variant="h4" sx={{ fontWeight: 800, mb: 3 }}>Tableau de bord</Typography>{error && <Alert severity="error">{error}</Alert>}<Grid container spacing={2}>{cards.map(([key, label]) => <Grid key={key} size={{ xs: 12, sm: 6, lg: 3 }}><Card><CardContent><Typography sx={{ color: 'text.secondary' }}>{label}</Typography><Typography variant="h4" sx={{ fontWeight: 700 }}>{key.toLowerCase().includes('rent') ? xof(data[key] ?? 0) : data[key] ?? 0}</Typography></CardContent></Card></Grid>)}</Grid></>
}

function LookupField({ field, defaultValue, disabled }: { field: Field; defaultValue: string; disabled?: boolean }) {
  const rows = useEntities(field.lookup!.endpoint)
  return <TextField select name={field.key} label={field.label} defaultValue={defaultValue} disabled={disabled} required><MenuItem value="" disabled>Sélectionner</MenuItem>{rows.map(row => <MenuItem key={row.id} value={row.id}>{String(row[field.lookup!.labelKey])}{field.lookup!.secondaryKey ? ` - ${String(row[field.lookup!.secondaryKey!] ?? '')}` : ''}</MenuItem>)}</TextField>
}

function ResourcePage({ title, endpoint, createEndpoint, fields, columns, allowEdit = true, allowDelete = true, allowTerminate = false }: { title: string; endpoint: string; createEndpoint?: string; fields: Field[]; columns: [string, string][]; allowEdit?: boolean; allowDelete?: boolean; allowTerminate?: boolean }) {
  const [rows, setRows] = useState<Entity[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [selected, setSelected] = useState<Entity | null>(null)
  const load = useCallback(() => { void api<Page<Entity>>(`${endpoint}?size=100`).then(p => setRows(p.content)).catch(e => setError(e.message)) }, [endpoint]); useEffect(() => { load() }, [load])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const raw = Object.fromEntries(new FormData(event.currentTarget)); const body: Record<string, unknown> = {}; for (const field of fields) { if (createEndpoint && field.key === 'propertyId') continue; body[field.key] = field.type === 'number' ? Number(raw[field.key]) : raw[field.key] || null }
    try { let url = endpoint; if (!selected && createEndpoint) url = createEndpoint.replace('{propertyId}', String(raw.propertyId)); else if (selected) url = `${endpoint}/${selected.id}`; await api(url, { method: selected ? 'PUT' : 'POST', body: JSON.stringify(body) }); setOpen(false); setSelected(null); load() } catch (e) { setError((e as Error).message) } }
  async function terminate(row: Entity) { const date = prompt('Date de fin du bail (AAAA-MM-JJ)', new Date().toISOString().slice(0, 10)); if (!date) return; try { await api(`${endpoint}/${row.id}/terminate?date=${encodeURIComponent(date)}`, { method: 'POST' }); load() } catch (e) { setError((e as Error).message) } }
  return <><Stack direction="row" sx={{ justifyContent: 'space-between', mb: 3 }}><Typography variant="h4" sx={{ fontWeight: 800 }}>{title}</Typography><Button variant="contained" onClick={() => { setSelected(null); setOpen(true) }}>Ajouter</Button></Stack>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<TableContainer component={Paper}><Table><TableHead><TableRow>{columns.map(([, label]) => <TableCell key={label}>{label}</TableCell>)}<TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(row => <TableRow key={row.id}>{columns.map(([key]) => <TableCell key={key}>{String(row[key] ?? '')}</TableCell>)}<TableCell>{allowEdit && <Button onClick={() => { setSelected(row); setOpen(true) }}>Modifier</Button>}{allowDelete && <Button color="error" onClick={async () => { if (confirm('Confirmer la suppression ?')) { await api(`${endpoint}/${row.id}`, { method: 'DELETE' }); load() } }}>Supprimer</Button>}{allowTerminate && row.status === 'ACTIVE' && <Button color="warning" onClick={() => terminate(row)}>Terminer</Button>}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Dialog open={open} onClose={() => setOpen(false)} fullWidth><Stack component="form" onSubmit={submit}><DialogTitle>{selected ? 'Modifier' : 'Créer'} {title.toLowerCase()}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}>{fields.map(field => field.lookup ? <LookupField key={field.key} field={field} defaultValue={String(selected?.[field.key] ?? '')} disabled={Boolean(selected && createEndpoint && field.key === 'propertyId')} /> : field.options ? <TextField key={field.key} select name={field.key} label={field.label} defaultValue={String(selected?.[field.key] ?? field.options[0])}>{field.options.map(option => <MenuItem key={option} value={option}>{option}</MenuItem>)}</TextField> : <TextField key={field.key} name={field.key} label={field.label} type={field.type ?? 'text'} defaultValue={String(selected?.[field.key] ?? '')} required={!['description', 'email', 'address', 'identityReference', 'endDate'].includes(field.key)} />)}</Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Annuler</Button><Button type="submit" variant="contained">Enregistrer</Button></DialogActions></Stack></Dialog></>
}

function Billing() {
  const [rows, setRows] = useState<Entity[]>([]); const [error, setError] = useState(''); const [lease, setLease] = useState<Entity | null>(null); const leases = useEntities('/api/leases')
  const load = useCallback(() => { void api<Page<Entity>>('/api/rent-charges?size=100').then(p => setRows(p.content)).catch(e => setError(e.message)) }, []); useEffect(() => { load() }, [load])
  async function pay(id: string, balance: number) { const value = prompt(`Montant à enregistrer (solde ${balance} XOF)`); if (!value) return; try { await api(`/api/rent-charges/${id}/payments`, { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ amount: Number(value), paymentDate: new Date().toISOString().slice(0, 10), method: 'CASH', reference: '' }) }); load() } catch (e) { setError((e as Error).message) } }
  async function reminder(id: string) { try { const result = await api<{ whatsappUrl: string }>(`/api/rent-charges/${id}/reminder-preview`, { method: 'POST' }); window.open(result.whatsappUrl, '_blank', 'noopener') } catch (e) { setError((e as Error).message) } }
  async function receipt(id: string) { try { const result = await api<{ id: string }>(`/api/rent-charges/${id}/receipt`, { method: 'POST' }); const response = await fetch(`/api/receipts/${result.id}/pdf`, { headers: { Authorization: `Bearer ${session.token()}` } }); if (!response.ok) throw new Error('Téléchargement impossible'); const url = URL.createObjectURL(await response.blob()); window.open(url) } catch (e) { setError((e as Error).message) } }
  const visibleRows = lease ? rows.filter(row => row.leaseId === lease.id) : rows
  return <><Typography variant="h4" sx={{ fontWeight: 800, mb: 3 }}>Loyers et paiements</Typography>{error && <Alert severity="error">{error}</Alert>}<Autocomplete sx={{ my: 2, maxWidth: 500 }} options={leases} value={lease} onChange={(_, value) => setLease(value)} getOptionLabel={option => `${String(option.startDate)} - ${xof(Number(option.monthlyRent))}`} renderInput={params => <TextField {...params} label="Filtrer par bail" />} /><TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Échéance</TableCell><TableCell>Dû</TableCell><TableCell>Payé</TableCell><TableCell>Solde</TableCell><TableCell>Statut</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{visibleRows.map(row => <TableRow key={row.id}><TableCell>{String(row.dueDate)}</TableCell><TableCell>{xof(Number(row.amountDue))}</TableCell><TableCell>{xof(Number(row.amountPaid))}</TableCell><TableCell>{xof(Number(row.balance))}</TableCell><TableCell>{String(row.status)}</TableCell><TableCell><Button disabled={Number(row.balance) === 0} onClick={() => pay(row.id, Number(row.balance))}>Paiement</Button><Button disabled={Number(row.balance) === 0} onClick={() => reminder(row.id)}>WhatsApp</Button><Button disabled={Number(row.balance) !== 0} onClick={() => receipt(row.id)}>Quittance</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></>
}

const ownerLookup: Lookup = { endpoint: '/api/owners', labelKey: 'fullName', secondaryKey: 'phone' }
const propertyLookup: Lookup = { endpoint: '/api/properties', labelKey: 'name', secondaryKey: 'city' }
const unitLookup: Lookup = { endpoint: '/api/units', labelKey: 'name', secondaryKey: 'type' }
const tenantLookup: Lookup = { endpoint: '/api/tenants', labelKey: 'fullName', secondaryKey: 'phone' }

function ProtectedApp() { return <Shell><Routes><Route path="/" element={<Dashboard />} /><Route path="/owners" element={<ResourcePage title="Propriétaires" endpoint="/api/owners" fields={[{ key: 'fullName', label: 'Nom complet' }, { key: 'phone', label: 'Téléphone' }, { key: 'email', label: 'Email' }, { key: 'address', label: 'Adresse' }]} columns={[["fullName", "Nom"], ["phone", "Téléphone"], ["email", "Email"]]} />} /><Route path="/properties" element={<ResourcePage title="Biens" endpoint="/api/properties" fields={[{ key: 'ownerId', label: 'Propriétaire', lookup: ownerLookup }, { key: 'name', label: 'Nom' }, { key: 'description', label: 'Description' }, { key: 'address', label: 'Adresse' }, { key: 'city', label: 'Ville' }, { key: 'type', label: 'Type', options: ['APARTMENT_BUILDING', 'HOUSE', 'VILLA', 'COMMERCIAL', 'LAND'] }, { key: 'status', label: 'Statut', options: ['AVAILABLE', 'OCCUPIED', 'MAINTENANCE'] }]} columns={[["name", "Nom"], ["city", "Ville"], ["type", "Type"], ["status", "Statut"]]} />} /><Route path="/units" element={<ResourcePage title="Unités" endpoint="/api/units" createEndpoint="/api/properties/{propertyId}/units" fields={[{ key: 'propertyId', label: 'Bien', lookup: propertyLookup }, { key: 'name', label: 'Nom' }, { key: 'type', label: 'Type', options: ['APARTMENT', 'ROOM', 'SHOP', 'OFFICE'] }, { key: 'status', label: 'Statut', options: ['AVAILABLE', 'OCCUPIED', 'MAINTENANCE'] }, { key: 'description', label: 'Description' }, { key: 'monthlyRent', label: 'Loyer mensuel', type: 'number' }]} columns={[["name", "Nom"], ["type", "Type"], ["status", "Statut"], ["monthlyRent", "Loyer XOF"]]} />} /><Route path="/tenants" element={<ResourcePage title="Locataires" endpoint="/api/tenants" fields={[{ key: 'fullName', label: 'Nom complet' }, { key: 'phone', label: 'Téléphone' }, { key: 'email', label: 'Email' }, { key: 'address', label: 'Adresse' }, { key: 'identityReference', label: 'Référence identité' }]} columns={[["fullName", "Nom"], ["phone", "Téléphone"], ["email", "Email"]]} />} /><Route path="/leases" element={<ResourcePage title="Baux" endpoint="/api/leases" allowEdit={false} allowDelete={false} allowTerminate fields={[{ key: 'unitId', label: 'Unité', lookup: unitLookup }, { key: 'tenantId', label: 'Locataire', lookup: tenantLookup }, { key: 'startDate', label: 'Date début', type: 'date' }, { key: 'endDate', label: 'Date fin', type: 'date' }, { key: 'monthlyRent', label: 'Loyer', type: 'number' }, { key: 'depositAmount', label: 'Caution', type: 'number' }, { key: 'dueDay', label: 'Jour échéance', type: 'number' }]} columns={[["startDate", "Début"], ["monthlyRent", "Loyer XOF"], ["depositAmount", "Caution"], ["status", "Statut"]]} />} /><Route path="/billing" element={<Billing />} /></Routes></Shell> }
export default function App() { return <BrowserRouter><Routes><Route path="/login" element={<Login />} /><Route path="/*" element={session.token() ? <ProtectedApp /> : <Navigate to="/login" />} /></Routes></BrowserRouter> }
