package sn.gestionimmobiliere.backend.billing.domain;
import java.time.*;import java.util.UUID;import jakarta.persistence.*;
@Entity @Table(name="rent_charges") public class RentCharge{
	@Id private UUID id;@Column(name="organization_id")private UUID organizationId;@Column(name="lease_id")private UUID leaseId;@Column(name="period_start")private LocalDate periodStart;@Column(name="due_date")private LocalDate dueDate;@Column(name="amount_due")private long amountDue;@Column(name="amount_paid")private long amountPaid;@Enumerated(EnumType.STRING)private ChargeStatus status;@Column(name="created_at")private Instant createdAt;@Column(name="updated_at")private Instant updatedAt;
	protected RentCharge(){}public RentCharge(UUID id,UUID org,UUID leaseId,LocalDate periodStart,LocalDate dueDate,long amount,LocalDate today,Instant now){this.id=id;organizationId=org;this.leaseId=leaseId;this.periodStart=periodStart;this.dueDate=dueDate;amountDue=amount;status=dueDate.isBefore(today)?ChargeStatus.OVERDUE:dueDate.isEqual(today)?ChargeStatus.DUE:ChargeStatus.UPCOMING;createdAt=now;updatedAt=now;}
	public void pay(long amount,LocalDate today,Instant now){if(amountPaid+amount>amountDue)throw new IllegalArgumentException("Le paiement depasse le solde de l'echeance");amountPaid+=amount;status=amountPaid==amountDue?ChargeStatus.PAID:amountPaid>0?ChargeStatus.PARTIAL:dueDate.isBefore(today)?ChargeStatus.OVERDUE:ChargeStatus.DUE;updatedAt=now;}
	public void refresh(LocalDate today,Instant now){if(status!=ChargeStatus.PAID&&status!=ChargeStatus.CANCELLED){status=amountPaid>0?ChargeStatus.PARTIAL:dueDate.isBefore(today)?ChargeStatus.OVERDUE:dueDate.isEqual(today)?ChargeStatus.DUE:ChargeStatus.UPCOMING;updatedAt=now;}}
	public UUID getId(){return id;}public UUID getOrganizationId(){return organizationId;}public UUID getLeaseId(){return leaseId;}public LocalDate getPeriodStart(){return periodStart;}public LocalDate getDueDate(){return dueDate;}public long getAmountDue(){return amountDue;}public long getAmountPaid(){return amountPaid;}public long getBalance(){return amountDue-amountPaid;}public ChargeStatus getStatus(){return status;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}
}
